# tunnel: b0654952-43b1-4f55-96e2-de729c747a1f  # Replace with your actual tunnel ID
#env_file:
#  - ./.env
# token: ${CLOUDFLARE_TUNNEL_TOKEN}
ingress:
  # Route your chosen subdomain (which should be configured in your Cloudflare dashboard) to nginx
  - hostname: ai.goessforest.com
    service: https://nginx:443
  - service: http_status:404
